### ISSUE TITLE
Not going beyond the Login with Google screen

### ISSUE THREAD

**Issue by krishnakanthpps** [birender-s/ticketing-client-android#1]
Good work. Since this is an MIT license, I was trying to have it tweaked.

But in its current shape, it doesnt go beyond the login screen. 

I select the gmail ID i want to login with, but the screen refreshes and come back to the same screen. 

I wonder why. 

Any suggestions.

mine is a LeTV phone. Using Android SDK to deploy.

**Comment by krishnakanthpps** [comment]
Infoscions, Any plan to work on the issue that I have? 

Thank you.

**Comment by birender-s** [comment]
Hi Krishna,
Firstly, Sorry for the delayed response.
The reason you're stuck up is bacuse Google Sign-in requires google-services.json file containing API key and other details. This is developer specific so you would need to login to your developer account and add appropriate details. 
You can however checkout below branch and run app in RELEASE build to get things going. We've added JSON from our account for now, that too in RELEASE build only. Please check and let me know if you're still facing any issues. All the Best !
https://github.com/birender-s/ticketing-client-android/tree/feedback_app

**Comment by krishnakanthpps** [comment]
Hey. Thank you. I was actually looking for this input as I knew you had to put Google Auth info somewhere to have it integrated with Google Sign in.

Will try in a couple of days and let you know if I face any more issues.

Thank you very much for responding. And really great work.

**Comment by CammyKamal** [comment]
Hi Krishna,
Are you able to resolve the issue?

**Comment by krishnakanthpps** [comment]
I havent got a chance to look at this particular one, but I believe it should be working. Will revert back if I find any issues.
